Assistant checkpoint: Move html-webpack-plugin to dependencies
Assistant generated file changes:
- package.json: Move html-webpack-plugin to dependencies

---

User prompt:

please fix this error. bubble-pop-react@1.0.0 start
> NODE_ENV=production webpack serve --mode production --port 80 --host 0.0.0.0

[webpack-cli] Failed to load '/home/runner/bubble-pop-react/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'html-webpack-plugin'
Require stack:
- /home/runner/bubble-pop-react/webpack.config.js
- /home/runner/bubble-pop-react/node_modules/webpack-cli/lib/webpack-cli.js
- /home/runner/bubble-pop-react/node_modules/webpack-cli/lib/bootstrap.js
- /home/runner/bubble-pop-react/node_modules/webpack-cli/bin/cli.js
- /home/runner/bubble-pop-react/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/runner/bubble-pop-react/webpack.config.js:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/bubble-pop-react/webpack.config.js',
    '/home/runner/bubble-pop-react/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/runner/bubble-pop-react/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/runner/bubble-pop-react/node_modules/webpack-cli/bin/cli.js',
    '/home/runner/bubble-pop-react/node_modules/webpack/bin/webpack.js'
  ]
}